# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - ohteam4fn

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ .github/** ] 

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1' # set this to the dotnet version to use
  PRODUCTION_SLOT: false

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action - Production'
        if: ${{ env.PRODUCTION_SLOT == true }}
        uses: Azure/functions-action@v1
        id: faproduction
        with:
          app-name: 'ohteam4fn'
          slot-name: 'production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_060F1375D4474EA093BD1B0414C2BC80 }}

      - name: 'Run Azure Functions Action - Staging'
        if: ${{ env.PRODUCTION_SLOT == false }}
        uses: Azure/functions-action@v1
        id: fastaging
        with:
          app-name: 'ohteam4fn'
          slot-name: 'ohteam4fn-staging'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.OHTEAM4FNAPP_STAGING }}